problems284_d.py
